# Generated by Django 4.2.5 on 2023-10-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=122)),
                ('lname', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('contact', models.CharField(max_length=122)),
                ('message', models.CharField(max_length=1222)),
            ],
        ),
    ]
