# Generated by Django 4.2.5 on 2023-10-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact',
        ),
    ]
